// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/feature/repository/port/feature_repository.go

// Package mock_port is a generated GoMock package.
package mock_port

import (
        reflect "reflect"

        entity "github.com/cambiar_api/internal/entity"
        gomock "github.com/golang/mock/gomock"
)

// MockIFeatureRepository is a mock of IFeatureRepository interface.
type MockIFeatureRepository struct {
        ctrl     *gomock.Controller
        recorder *MockIFeatureRepositoryMockRecorder
}

// MockIFeatureRepositoryMockRecorder is the mock recorder for MockIFeatureRepository.
type MockIFeatureRepositoryMockRecorder struct {
        mock *MockIFeatureRepository
}

// NewMockIFeatureRepository creates a new mock instance.
func NewMockIFeatureRepository(ctrl *gomock.Controller) *MockIFeatureRepository {
        mock := &MockIFeatureRepository{ctrl: ctrl}
        mock.recorder = &MockIFeatureRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFeatureRepository) EXPECT() *MockIFeatureRepositoryMockRecorder {
        return m.recorder
}

// GetAllWithQuery mocks base method.
func (m *MockIFeatureRepository) GetAllWithQuery() []entity.Feature {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllWithQuery")
        ret0, _ := ret[0].([]entity.Feature)
        return ret0
}

// GetAllWithQuery indicates an expected call of GetAllWithQuery.
func (mr *MockIFeatureRepositoryMockRecorder) GetAllWithQuery() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithQuery", reflect.TypeOf((*MockIFeatureRepository)(nil).GetAllWithQuery))
}